//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_WPF.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBHospitalEntities : DbContext
    {
        private static DBHospitalEntities _context;

        public static DBHospitalEntities GetContext()
        {
            if (_context == null)
                _context = new DBHospitalEntities();
            return _context;
        }

        public DBHospitalEntities()
            : base("name=DBHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access_Level_Table> Access_Level_Table { get; set; }
        public virtual DbSet<Diagnoses_Table> Diagnoses_Table { get; set; }
        public virtual DbSet<Doctors_Table> Doctors_Table { get; set; }
        public virtual DbSet<Gender_Table> Gender_Table { get; set; }
        public virtual DbSet<Patients_Medical_Records_Table> Patients_Medical_Records_Table { get; set; }
        public virtual DbSet<Reception_Table> Reception_Table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
