//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_WPF.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnoses_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnoses_Table()
        {
            this.Reception_Table = new HashSet<Reception_Table>();
        }
    
        public int id_diagnose { get; set; }
        public string Name_diagnose_rus { get; set; }
        public string Name_diagnose_lat { get; set; }
        public string Type_diagnose { get; set; }
        public string Nature_of_the_disease { get; set; }
        public string Stage_diagnose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception_Table> Reception_Table { get; set; }
    }
}
