//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_WPF.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors_Table()
        {
            this.Reception_Table = new HashSet<Reception_Table>();
        }
    
        public int id_doctor { get; set; }
        public string Name_doctor { get; set; }
        public string Surname_doctor { get; set; }
        public string Patronymic_doctor { get; set; }
        public string Specialization { get; set; }
        public int Experience { get; set; }
        public string User_login { get; set; }
        public string User_pass { get; set; }
        public int id_access_level { get; set; }
        public byte[] EmployeeImage { get; set; }
    
        public virtual Access_Level_Table Access_Level_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception_Table> Reception_Table { get; set; }
    }
}
