//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_WPF.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gender_Table()
        {
            this.Patients_Medical_Records_Table = new HashSet<Patients_Medical_Records_Table>();
        }
    
        public int id_gender { get; set; }
        public string Name_of_gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients_Medical_Records_Table> Patients_Medical_Records_Table { get; set; }
    }
}
