//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_WPF.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients_Medical_Records_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients_Medical_Records_Table()
        {
            this.Reception_Table = new HashSet<Reception_Table>();
        }
    
        public int id_medical_records { get; set; }
        public string Name_patient { get; set; }
        public string Surname_patient { get; set; }
        public string Patronymic_patient { get; set; }
        public int Age_patient { get; set; }
        public System.DateTime Birth_date_patient { get; set; }
        public int id_gender { get; set; }
        public string Insurance_policy_number_patient { get; set; }
        public string Addres_patient { get; set; }
    
        public virtual Gender_Table Gender_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception_Table> Reception_Table { get; set; }
    }
}
