//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_WPF.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception_Table
    {
        public int id_reception { get; set; }
        public int id_doctor_reception { get; set; }
        public int id_medical_records_reception { get; set; }
        public System.DateTime Date_of_reception { get; set; }
        public string Complaints { get; set; }
        public string Appointment { get; set; }
        public int id_diagnose_reception { get; set; }
        public string addition_to_diagnose { get; set; }
    
        public virtual Diagnoses_Table Diagnoses_Table { get; set; }
        public virtual Doctors_Table Doctors_Table { get; set; }
        public virtual Patients_Medical_Records_Table Patients_Medical_Records_Table { get; set; }
    }
}
